var n;Array.prototype.Kb||(Array.prototype.Kb=function(a){0>a&&(a+=this.length);return this[a]});Array.prototype.includes||(Array.prototype.includes=function(a,b){return 0<=this.indexOf(a,b)});NodeList.prototype[Symbol.iterator]||(NodeList.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);HTMLCollection.prototype[Symbol.iterator]||(HTMLCollection.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);
const aa=Boolean,r=Object.isExtensible,x=RegExp.prototype.test,ba=RegExp.prototype.exec,ca=Array.isArray,da=Array.from,ea=Array.prototype.includes;Array.prototype.concat.bind([]);const fa=Function.call.bind(Array.prototype.slice),ha=Function.apply.bind(Array.prototype.push),ia=Function.apply.bind(String.fromCharCode,null),y=Math.floor,z=Math.random,B="undefined"==typeof browser;B&&(browser=chrome);
const D=navigator.userAgent.includes("Edge/"),ja=navigator.userAgent.includes("Edg/"),F=navigator.userAgent.includes("Firefox/"),ka=navigator.userAgent.includes("OPR/"),la=navigator.userAgent.includes("YaBrowser/");var G=0,ma,na,qa,ra,sa;const H="undefined"==typeof globalThis?this:globalThis,ta=F?69:D?77:66,ua=F?220:150,I=browser.runtime.getManifest();var va=I.permissions.includes("notifications")||null;
const wa={16:"images/logo16.png",32:"images/logo32.png"},xa={16:"images/logo16x.png",32:"images/logo32x.png"},ya=["127.0.0.1:1001","0.1.0.1:1001"],za=B?"Chrome_RenderWidgetHostHWND":F?"MozillaWindowClass":D?"Windows.UI.Core.CoreWindow":null,Aa=/(?!)/,Ba=["main_frame","sub_frame"],Ca=["object","image"];var J=Ca.concat("xmlhttprequest",D?"other":[]),Da=Ba.concat(Ca,"xmlhttprequest","other");
const L=["*://*/*"],Ea=["ftp://*/*"],Fa=L.concat(Ea,"file:///*",B?"about:blank":[]),Ga=L.concat(B?"about:blank":[]),Ha=B&&btoa(z().toString().substr(2,9)),Ia=browser.runtime.getURL("captured.html?"+(Ha?"auth="+Ha+"&":"")),Ja=browser.runtime.getURL("welcome.html?"+(Ha?"auth="+Ha+"&":"")),Ka=browser.runtime.getURL("").slice(0,-1),La=location.href,Ma=ka||la,Na=B||D,Oa=!F;var Pa=B;
const Qa=x.bind(/^(?:chrome|about|chrome-extension|chrome-search|ms-browser-extension|ms-appx-web|moz-extension):/),Ra=x.bind(/^(?:Host|Origin|Referer|Cookie|User-Agent|Connection|DNT|Accept-Encoding|Sec-.+)$/i),Sa=x.bind(/^(?:application\/(?:json|x-javascript)|text\/(?:javascript|plain))$/),Ta=x.bind(/^(HTM|HTML|CGI|PHP|ASP|ASPX|JSP|JSPX)$/i),Ua=x.bind(/^(MPD|M3U8|F4M)$/i),Va=x.bind(/^ftp:|^idmreg:|\bidman|\binternetdownloadmanager\b/i),Wa=x.bind(/^[GPTSDVACRHX]*$/),Xa=ba.bind(/^(.*?)(,\s*)?\bapplication\/vnd\.t1c\.([^\s,]+)(?:,\s*)?(.*)$/);
ba.bind(/:\/\/.+\/([^/]+?(?:\.([^./]+?))?)(?=[?#]|$)/);
const Ya=ba.bind(/\.([^.\\/]*?)(?:\.[0-9.]+)?$/),Za=ba.bind(/^v(\d+)\.(\d+)(?:b(\d+))?\b/),$a=ea.bind([301,302,303,307,308]),ab=ea.bind([301,302,303]),bb=/[:,;]/,cb=/[,;]/,db=x.bind(/messaging host not found|no such native application|application is not installed/i),eb=x.bind(/^(?:https?|socks[45])$/),fb={direct:2,auto_detect:3,system:4,pac_script:5,fixed_servers:7},gb=[],hb={"-1":[2,[111,112],[111]],1:[2,[115,116,117,124,118,119,120,121,127,123,125,126,129,130],[115,111,112,113,114]],2:[2,[114,113,
113,115,116,117,118,122,119,125,126,124,121,120,123,112],[111,112,114]],3:[null,[113,114,115,116,117],[112]],4:[2,[111,101,113,112,114,118,119,124,115,116,117,120,121,122,123],[111]],5:[null,[111,112,113],[111]],6:[null,[],[111]]},ib={16:1,17:2,18:4,45:8,46:16},jb={http:1,https:9,ftp:2,ftps:10,idmreg:12,xup:33},kb={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|VTT|SRT|M3U|PLS|M3U8|MPD|F4M|TORRENT|BTT","text/srt":"SRT","text/vtt":"VTT|SRT",
"text/xml":"XML|MPD|F4M|TTML|TTML2","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/dash+xml":"MPD","application/f4m+xml":"F4M|MPD","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/json+protobuf":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/ocsp-response":"OCSP","application/octet-stream-m3u8":"M3U8","application/pdf":"PDF","application/pkix-crl":"CRL","application/torrent":"TORRENT|BTT","application/ttaf+xml":"DFXP","application/ttml+xml":"TTML|TTML2",
"application/vnd.apple.mpegurl":"M3U8","application/vnd.yt-ump":"UMP","application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-bittorrent":"TORRENT|BTT","application/x-chrome-extension":"CRX","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-dosexec":"EXE","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8",
"application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI","application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F",
"video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|TSV|M3U8","video/mp4":"MP4|M4V|M4S","video/mpeg":"MPG|MPEG","video/mpegurl":"M3U|M3U8","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/vnd.mpeg.dash.mpd":"MPD","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U|M3U8","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP",
"audio/mp2t":"TS|TSA|M3U8","audio/mp3":"MP3","audio/mp4":"M4A|MP4|M4S","audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U|M3U8","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/avif":"AVIF","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR",
"image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};
function lb(a,b,c,e,d,f,h,k){if(a){var g=["MSG#",a,"#",b,"#",c,"#",e];this.f=a;this.type=b;this.m=c;this.flags=e;this.a=d||[];this.h=g;this.v=h;this.s=k;if(d)for(var l of d)g.push(":",l||0);if(f)for(var m in f)if(parseInt(m)&&(a=void 0,b=f[m],null!=b&&!this.g))switch(c=this.h,e=this.v,h=this.s,d=e&&h,h=h?"/":":",k=b instanceof String?"string":typeof b,c.push(",",m,"="),k){case "string":c.push(mb(b),":",b);break;case "number":c.push(b);break;case "boolean":c.push(b?1:0);break;case "object":if(b instanceof
Array){k=c.length;l=g=0;for(a of b)a instanceof ArrayBuffer||a instanceof Uint8Array?(e?(a=nb(a),g+=a.length):g+=a.byteLength,++l):(a=a.toString(),g+=mb(a)),c.push(a);l&&d?(b=btoa(c.splice(k).join("")),c.push(b.length,"%",b)):c.splice(k,0,g,l?h:":")}else b instanceof ArrayBuffer||b instanceof Uint8Array?d?(b=btoa(nb(b)),c.push(b.length,"%",b)):e?(b=nb(b),c.push(b.length,":",b)):c.push(b.byteLength,h,b):b instanceof Blob&&c.push(b.size,h,b)}}else this.l=new FileReader}
function ob(){this.a=ob.prototype.h++}ob.prototype.h=1;function pb(a,b,c,e){this.id=a;this.port=b;c&&(this.b=c=c.toLowerCase(),this.fa="iframe"==c);e&&(this.c=e)}pb.prototype.a=0;function qb(a,b,c){this.id=a+","+b;this.B=0==b;this.c=null==c||0>c?null:a+","+c}function rb(){}function sb(a){a.g||(a.h.push(";"),a.g=!0);return a.h.join("")}function tb(a){a.g||(a.h.push(";"),a.g=!0);return new Blob(a.h)}function ub(a,b,c){a.g?a.b(a):(b.a=c||0,b.b=0,a.l.onload=a.o.bind(a,b),vb(a,b,0,50))}
lb.prototype.o=function(a){for(var b=this.l.result;;)switch(a.b){case 0:var c=b.search(bb);if(0>=c)return this.b(this);var e=b[c],d=b.slice(0,c++).split("#",6);if(5!=d.length||"MSG"!=d[0])return this.b(this);this.f=parseInt(d[1]);this.type=parseInt(d[2]);this.m=parseInt(d[3]);this.flags=parseInt(d[4]);b=b.slice(c);a.a+=c;a.b=":"==e?1:","==e?2:5;break;case 1:c=b.search(cb);if(0>=c)return c?vb(this,a,b.length,100):this.b(this);e=b[c];d=this.a=b.slice(0,c++).split(":");for(var f=0;f<d.length;f++){var h=
d[f];d[f]=h.includes(".")?parseFloat(h):parseInt(h)}b=b.slice(c);a.a+=c;a.b=","==e?2:5;break;case 2:c=b.search(bb);if(0>=c)return c?vb(this,a,b.length,25):this.b(this);e=b[c];d=b.slice(0,c++).split("=",3);if(2!=d.length)return this.b(this);f=parseInt(d[0]);d=parseInt(d[1]);a.a+=c;if(":"==e){a.f=f;a.c=d;a.b=3;b=a.c;c=a.a;a=a.slice(c,c+b);a.size==b?this.l.readAsText(a):this.b(this);return}this[f]=d;b=b.slice(c);a.b=","==e?2:5;break;case 3:return this[a.f]=b,a.a+=a.c,a.b=4,vb(this,a,0,21);case 4:switch(b[0]){case ",":a.b=
2;b=b.slice(1);break;case ";":a.b=5;break;default:return this.b(this)}a.a++;break;case 5:this.g=!0;this.i(this);a.size>a.a&&(b=new lb,b.i=this.i,b.b=this.b,ub(b,a,a.a));return}};function vb(a,b,c,e){var d=b.a;c=d+c;b.size>c?a.l.readAsBinaryString(b.slice(d,c+e)):a.b(a)}
function M(){var a=this.constructor.prototype,b;for(b in a)b.startsWith("_")||"constructor"==b||(this[b]=a[b].bind(this));this.l=0;this.G=null;this.ba=this.xa=0;this.qb=1;this.v=null;this.Ta=I.version||"";this.Fb="";this.ya=0;this.ua=!1;this.H=null;this.Ma=!1;this.N=null;this.hb=this.rb=this.Ja=this.o=!1;this.I=!F;this.Gb=this.ib=!0;this.jb=this.J=this.K=null;this.ub=this.ta=this.va=!1;this.pb=!0;this.Nc=this.Mc=1;this.La=this.m=this.ja=null;this.Na=1;this.Hb=0;this.U=this.S=this.Sa=null;this.nb=
Aa;this.ca=[];this.Ha=0;this.ob=null;this.Qa=this.Ka=!1;this.ka=this.s=null;this.za=Array(16);this.c={};this.h={};this.a={};this.D={};this.b={};this.ma={};this.g={};this.f={};this.wa={};this.ra={};this.i={};this.la={};this.sa={};this.sa.Hc=[];this.bb=[];browser.browserAction&&(wb(this,!1),browser.browserAction.onClicked.addListener(this.Ub));F&&1056964608<=G&&browser.contextMenus.onShown.addListener(this.Vb);F&&browser.runtime.onInstalled.addListener(this.Zb);browser.runtime.onMessage.addListener(this.$b);
browser.windows.onCreated.addListener(this.Bb);browser.windows.onRemoved.addListener(this.Cb);browser.windows.onFocusChanged.addListener(this.Cc);browser.windows.onBoundsChanged&&browser.windows.onBoundsChanged.addListener(this.Bc);browser.tabs.onActivated.addListener(this.rc);browser.tabs.onUpdated.addListener(this.uc);browser.tabs.onRemoved.addListener(this.tc);browser.tabs.onAttached&&browser.tabs.onAttached.addListener(this.sc);B&&1056964608<=G&&browser.webRequest.onBeforeRequest.addListener(this.Wb,
{urls:[browser.runtime.getURL("*")]},["blocking"]);this.Ic();this.Ib()}function xb(){}xb.prototype=[];var N=xb.prototype;xb=null;n=M.prototype;n.Vb=function(a,b){b&&yb(this,b.id,!0,!1,!0)};n.Zb=function(a){this.Ta=a.version=I.version;this.Jc=a};function zb(a,b){b&&browser.storage.local.set({consent:a.Ta});a.J=null;a.Oa(5);a.I=!0;Ab(a)}n.$b=function(a,b){switch(a[0]){case 38:a[1]&&this.ua&&browser.storage.local.set({silent:!0});browser.tabs.remove(b.tab.id);break;case 42:zb(this,!0);break;case 43:browser.management.uninstallSelf({showConfirmDialog:!0})}};
n.Ub=function(a){if(this.ub){if(this.J)return browser.windows.update(this.J,{focused:!0});var b=a.id,c=this.i[b];wb(this,c,b,!0);this.ta&&(c?(this.aa(a.windowId),Bb(this,b)):Cb(this,b))}};function wb(a,b,c,e){c?a.i[c]=!b:a.ub=b||e;Db(b,c,e)}
function Db(a,b,c){if(c||!b||!a){var e=a;F&&!b&&(a||c?browser.browserAction.enable():browser.browserAction.disable(),e=!0);c=a?Eb+Fb:b?Gb+Fb:c?Gb:Hb;var d=e?wa:xa,f=F&&b&&989855744<=G;if(D||B&&822083584>G)d=d[16];D||browser.browserAction.setTitle({title:a&&f?null:c,tabId:b});browser.browserAction.setIcon({path:e&&f?null:d,tabId:b});a||browser.browserAction.setBadgeBackgroundColor({color:"#606060"});browser.browserAction.setBadgeText({text:a?f?null:"":"X",tabId:b})}}
function Ab(a){var b=a.c,c=a.la={};browser.contextMenus.removeAll();for(var e=0;e<Ib.length;e++){var d=Ib[e];d[0]&&b[d[1]]&&(c[e]=browser.contextMenus.create({title:Jb(d[2]),contexts:d[3].split(","),onclick:d[4].bind(a),documentUrlPatterns:d[5]||Fa,enabled:!0}))}a.ta||(a.ta=!0,wb(a,!0),a.A(1,browser.runtime.onConnect,a.mc),B&&a.A(1,browser.proxy.settings.onChange,a.zb),B&&browser.proxy.settings.get({},a.zb),a.A(1,browser.webNavigation.onCreatedNavigationTarget,a.kc),a.A(1,browser.webNavigation.onCommitted,
a.yb),a.A(1,browser.webNavigation.onHistoryStateUpdated,a.bc),(b=a.c[17])&&a.A(2,browser.webRequest.onBeforeRequest,a.vc,{urls:b.split("|"),types:Ba},["blocking"]),Kb(a,!0),browser.tabs.query({url:L},a.Ba))}
function Kb(a,b){B&&a.o&&(browser.downloads.setUiOptions?browser.downloads.setUiOptions({enabled:!b}):browser.downloads.setShelfEnabled(!b));if(b){B&&a.o&&a.A(3,browser.downloads.onCreated,a.Xb);B&&a.o&&a.A(3,browser.downloads.onDeterminingFilename,a.Yb);b=ra?void 0:Da;const c=["blocking"],e=B&&!sa&&1207959552<=G?["extraHeaders"]:[];a.A(4,browser.webRequest.onBeforeRequest,a.Ab,{urls:Ea,types:Ba},c);a.A(4,browser.webRequest.onBeforeRequest,a.Ab,{urls:L,types:b},["requestBody"]);a.A(4,browser.webRequest.onBeforeSendHeaders,
a.xc,{urls:L,types:b},["requestHeaders"].concat(c,e));a.A(4,browser.webRequest.onHeadersReceived,a.zc,{urls:L,types:b},["responseHeaders"].concat(c));a.A(4,browser.webRequest.onResponseStarted,a.Ac,{urls:L,types:b});a.A(4,browser.webRequest.onErrorOccurred,a.yc,{urls:L,types:b});F&&a.A(4,browser.webRequest.onBeforeRedirect,a.wc,{urls:L,types:Ba})}else a.Oa(3,4)}
n.zb=function(a){browser.runtime.lastError;if(a){var b=a.value;a=fb[b.mode];var c,e;this.za.fill(void 0);if(5==a&&(e=b.pacScript))e.data&&5E4<e.data.length?a=4:(c=e.data)?(a=6,c=c.replace(/\blet\b/g,"var").replace(/,(?=(?:\s*\/\/.*?\n)*\s*[\]}])/g,"")):c=e.url,this.za.fill(!0);else if(7==a){b=b.rules;e=b.bypassList;c=Lb(this,b.singleProxy);if(!c){c=Lb(this,b.fallbackProxy);var d=Lb(this,b.proxyForHttp,1),f=Lb(this,b.proxyForHttps,9);b=Lb(this,b.proxyForFtp,2);d!=f||d!=b||d!=c&&c?(c=(d||"")+";"+(f||
"")+";"+(b||"")+";"+(c||""),++a):c=d}e&&e.length&&(c+=";"+e.join(","))}b=5>a?a.toString():c?a+":"+c:null;b!=this.s&&(this.s&&this.eb(),this.s=b)}};function Lb(a,b,c){if(b){var e=b.scheme||"http",d="https"==e;a=a.za;c?a[c]=d:a.fill(d);if(eb(e))return e+"://"+b.host+(b.port?":"+b.port:"")}}
function Mb(a,b,c,e){if(b){var d=b.type;if("direct"==d)return"0";"socks"==d&&(d="socks5");if(eb(d)){var f="1:"+d+"://"+b.host+":"+b.port;"socks5"==d&&b.proxyDNS&&(f+="#");c||e||!(c=a.ka)||(c=c.substr(c.indexOf(";")+1||c.length));c&&(f+=";"+c);e&&f&&(a.ka=f);return f}}}
n.eb=N[N.length]=function Nb(a,b){if(void 0===a){if((Oa||Pa)&&this.l){var e=this.S;e||(b="http://"+(1==this.l?(new URL(this.G.url)).host:ya[0]),e=b+"/status/204+IDM");a=new XMLHttpRequest;a.timeout=1E3;a.onreadystatechange=Nb.bind(this,a,b);a.open("GET",e,!0);a.send()}}else 4==a.readyState&&(204!=a.status?this.S=this.U=null:b&&(this.S=b+"/status/204+IDM",this.U=Oa&&this.H?b+"/client/"+this.H:null))};n.Ia=function(a,b,c,e){var d=this.g;return b in d?d[b]:d[b]=new pb(b,a,c,e)};
function Ob(a,b){a=a.f;var c=b.id;a[c]!==b&&(a[c]=b,D&&(a[b.requestId]=b));F&&b.Ga&&(a[b.Ga]=b)}function Pb(a,b,c,e,d){if(r(b)){var f=b.frameId||0;var h=b.parentFrameId;var k=b.method&&b.id;e||(e=b.tabId);d||(d=b.url)}else f=b;var g=a.D[e+","+f];g||(g=new qb(e,f,h),a.D[g.id]=g);k?(g.f!=k&&(g.f=k,g.i=d,g.C=!1,g.b&&(g.b=d.startsWith(b.initiator||b.originUrl))),g.g="POST"==b.method):d&&(d.startsWith("about:blank")?f&&(g.b=!0):g.j=d);null!=c&&(g.refresh=c);return g}
function Qb(a,b){return a.D[b.tabId+","+b.frameId]}function Tb(a){var b=new ob;return a.ma[b.a]=b}function Ub(a,b){var c;b instanceof ob?c=b.a:b=a.ma[c=b];delete a.ma[c];return b}function Vb(a,b){for(var c of a.ca)if(c&&c[101].test(b))return c.ha;return 0}
n.Pa=function(){var a=this.xa%(ya.length+1);if(a<ya.length){a=ya[a];var b=this.H||0,c=z().toString().substr(2,9);a=this.G=new WebSocket("ws://"+a+"/?cid="+b+"&rnd="+c,"plugin.v3.internetdownloadmanager.com");a.onopen=this.Xa;a.onclose=this.X;a.onmessage=this.qc;a.onerror=O;1==a.readyState?this.Xa(1):3==a.readyState?this.X():this.v=H.setTimeout(this.X,1500,a)}else D?this.X():(a=this.G=browser.runtime.connectNative("com.tonec.idm"),a.onDisconnect.addListener(this.X),a.onMessage.addListener(this.cc),
this.v=H.setTimeout(this.Xa,0,2))};n.Xa=function(a){this.v&&(H.clearTimeout(this.v),this.v=null);this.l=r(a)?1:a;this.qb=1;this.ua=!1;a=browser.i18n.getUILanguage().replace("_","-");"sr"==a&&(a+="-Cyrl-CS");var b=[101,72,Ma?1028:1031,0,16845059,this.H],c={};c[112]=na;c[113]=ma;c[114]=za;c[125]=JSON.stringify(this.Jc);c[116]=a;P(this,2,3,Ma?0:1024,b,c)};
n.X=function(a){this.v&&(H.clearTimeout(this.v),this.v=null);var b=browser.runtime.lastError||a&&a.error,c=this.G;if(c instanceof WebSocket){if(a===c)return c.close()}else c&&db(b&&b.message)&&(this.ua=!0);this.G=null;this.l&&(this.l=0,this.wa={},Kb(this,!1),this.Oa(1,2),this.ta=!1,this.s=this.U=this.S=null,wb(this,!1));a=++this.xa;b=ya.length+1;c=a/b;120>c&&(1==c&&Wb(this),!a||a%b?this.Pa():H.setTimeout(this.Pa,5E3*c))};
n.wb=function(){var a=this.G;a instanceof WebSocket?a.close():a&&(a.disconnect(),this.X())};n.qc=function(a){var b=new lb;b.i=this.xb;b.b=this.wb;ub(b,a.data)};n.cc=function(a){var b=new lb;b.i=this.xb;b.b=this.wb;ub(b,new Blob([a]))};
function P(a,b,c,e,d,f,h){var k=a.ba,g=a.l;if(!g)return 0;1==b&&92>k&&4>d.length&&(d.length=4);var l=a.qb++;b=new lb(l,b,c,e,d,f,2==g,99<=k);if(h)return h.open("POST",a.U+"?seq="+l,!1),h.send(tb(b)),200==h.status?l:0;if(1==g)a.G.send(tb(b));else try{a.G.postMessage(sb(b))}catch(m){return a.X(),0}e&1&&(a.wa[l]=b);return l}
function Xb(a,b){if(b.a){var c=b.a[1],e=a.f[c];if(e)return e.V?b.c=e.port.id:null;e=a.h;for(var d in e)if(e[d].c==c)return b.c=d}d=b[6];e=b[17];var f=b[50],h=b[7],k=a.sa,g=a.g;a=a.a;var l;if((l=k[d])||(l=k[e]))return b.c=l.id;if(l=k[f])var m=l.id;for(c in g){k=g[c];var p=k.c;if(p){if(p==d||p==e||p==f){l=k.port;if(h){var q=a[l.tabId];q&&q.j!=h&&(l=null)}if(l)return b.c=l.id}if(p==h)var t=k.port.id}}return m?b.c=m:t?b.c=t:null}
n.Ob=N[N.length]=function Yb(a,b,c,e){var f;a:for(;!c;){if(f=a.c)return f;if(a.a){var h=this.a[a.a[6]+","+a.a[7]];h?f=h.id:(h=a.a[7])&&this.h[h]&&(f=h)}if(f||(f=Xb(this,a)))break;var k=this.h,g=a[50],l=a[7],m;for(m in k){h=k[m];if(h.j==g){f=m;break a}h.j==l&&(f=m)}if(f)break;return l?browser.tabs.query({url:l},Yb.bind(this,a,b,!0)):null}return c?(browser.runtime.lastError,e&&(e=e.shift())&&(h=this.a[e.id])&&(f=a.c=h.id),b&&b(f)):a.c=f};
n.kb=N[N.length]=function Zb(a,b,c){var d=a.tabId,f=a.O;if(b)if(ca(c))for(var h=a.j,k=h.includes("#")&&$b(h),g=c.length;g--;){b=c[g];var l=b.frameId;if(l!=f)if(l&&!b.Zc&&(b.url==h||k&&b.url==k))f=a.O=l;else continue;var m=b.parentFrameId;break}else c?m=c.parentFrameId:browser.runtime.lastError;else if(0<f?!a.b:null==f){if(f&&822083584<=G)return browser.webNavigation.getFrame({frameId:f,tabId:d},Zb.bind(this,a,!0));if(f||a.j)return browser.webNavigation.getAllFrames({tabId:d},Zb.bind(this,a,!0))}0<=
m&&(a.b=d+","+m);if(null!=f&&a.g){if(b=this.D[d+","+f])a.c=b.f,a.C|=b.C,a.refresh|=b.refresh,a.i=b.b,(c=b.Y)&&a.j!=c&&(a.Y=c),a.b||(a.b=b.c),(c=this.f[a.c])&&!c.port&&(c.port=a);this.a[d+","+f]=a;m=this.Ja?1:null;c=a.ha;d=[11,this.ba,a.id,d,f,c,a.refresh,a.C,m&&gb[m]];c&&a.C&&(f=this.ca[c],d.push(gb[f.Pb]),ha(d,f.Mb.map(ac(f)).map(bc)));a.postMessage(d)}};
n.ia=N[N.length]=function cc(a,b,c,e,d,f,h,k){var l=dc(a);if(l){var m=0<(l&32),p=1==(l&=7);if(p&&!m&&!h)return Q(a,cc.bind(this,a,b,c,e,d,f,!0));h=[l];l={};l[6]=$b(a,p,this);l[50]=b;l[7]=c;l[8]=e;l[100]=d;l[102]=f;l[51]=R(k);l[54]=navigator.userAgent;l[121]=F?this.ka:this.s;P(this,14,1,0,h,l)}};
n.Kc=N[N.length]=function ec(a,b,c,e,d,f){if(a&&a.length){if(c){var k=c.c;var g=c.U;var l=c.l}if(!e){if(!a||!a.length)return;f=fc();k&&!g&&Q(k,d=T());for(var m of a)Q(m[0],f[f.length]=T());return U(ec,this,a,b,c,!0,d,f)}d&&(g=R(d));for(m of a)m[5]=R(f.shift());b=0;c=[0,0,0];e={8:4};e[54]=navigator.userAgent;e[7]=k;e[110]=l;e[111]=g;e[121]=F?this.ka:this.s;1<a.length&&(c[1]=P(this,15,1,0,[a.length],e),b=16,e={});for(m of a)c[2]++,e[6]=m[0],e[100]=m[2],e[102]=m[3],e[50]=m[4],e[51]=m[5],P(this,14,2,
b,c,e)}};n.Ra=function(a,b){if(!this.l)return gc(b.id,"cannot_contact_idm");var c=a.linkUrl,e=a.pageUrl,d=e;if(a.menuItemId==this.la[4])return browser.downloads.search({query:[c]},this.Nb.bind(this,c));if(a.menuItemId==this.la[1])c=a.frameUrl,c&&"about:blank"!=c||(c=e,d=null);else if(!c&&(c=a.srcUrl,(a=this.a[b.id+","+a.frameId])&&c)){var f=Tb(this);f.tabId=b.id;f.port=a;f.i=c;f.m=d;f.c=e;f.flags=4;return a.postMessage([18,f.a,c])}c&&this.ia(c,d,e,4)};
n.fb=function(a,b){if(!this.l)return gc(b.id,"cannot_contact_idm");yb(this,b.id,a.menuItemId==this.la[2])};n.Nb=function(a,b){for(var c,e,d;c=b.pop();)c.exists&&"complete"==c.state?e||d||(d=c.referrer):(e||(e=c.referrer),browser.downloads.erase({id:c.id}));this.ia(a,e||d,null,4)};
function yb(a,b,c,e,d,f,h,k,g){if(!e||a.c[-5]){var l=a.a[b];if(l){var m=Tb(a);m.tabId=b;m.port=l;m.G=c;m.I=d;m.b=0;m.f=[];if(l=e&&!!f)m.N=!0,m.S=f,m.s=h,m.v=k,m.o=g,f.B||hc(a,f);f=m.a;(e=e&&a.c[12])?(e=e.replace(/\./g,"\\.").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"),e="^(?:http|https|ftp|ftps)://(?:[^\\/]*@)?(?:"+e+")(?::\\d+)?(?:\\W|$)"):e="^(?:http|https|ftp|ftps)://";m.g=ic(a,b,[12,f,c,l||d,e]);m.D=0;m.g||Ub(a,m)}}}
n.Ec=function(a,b,c,e,d,f,h,k){if(a=this.ma[b]){e&&(a.b+=e);h&&(a.c=h);k&&(a.l=k);if(d&&("string"==typeof d&&(d=JSON.parse(d)),d instanceof Array)){if(f)for(var g of d)g[4]=f;ha(a.f,d)}++a.D<a.g||(a.N?(e=a.tabId,(d=this.b[a.port.a])&&d.u==e&&a.b&&(f=a.o,h=d.b,k=d.a,P(this,10,1,0,[4294967295,d.m,Math.round(a.s*f+(d.h+h)*k),Math.round(a.v*f+(d.G+h)*k),0,a.b]),this.m=e,ic(this,e,[13,!0]))):a.I?(e=0<a.b,this.pb!=e&&(this.pb=e,browser.contextMenus.update(this.la[2],{visible:e}),browser.contextMenus.refresh())):
(e=a.f,e.length?this.Kc(e,a.G,a):gc(a.tabId,"cannot_find_links")),Ub(this,a))}};n.ic=function(a,b,c,e){(a=Ub(this,b))&&this.ia(a.i,a.m,a.c,a.flags,c,e)};n.Xb=function(a){(this.o||a.byExtensionId)&&!this.Qa&&this.c[-6]&&dc(a.finalUrl||a.url,!0)&&(this.ra[a.id]=a,browser.downloads.pause(a.id,O))};
n.Yb=function(a,b){var c=a.id,e=this.ra;if(!e[c])return!1;var d=this.c,f=a.finalUrl||(a.finalUrl=a.url),h=new URL(f),k=a.R=dc(f,!0),g=a.pa=jc(a.filename||h.pathname);if(!(a.da=this.Ka)&&!this.o&&(!d[1].test(g)||d[9].test(h.hostname)||d[19].test(h.href)))return kc(this,c);a.Lc=b;e[c]=a;if(1==k){if(!a.referrer){b=this.b;for(var l of V(this.h))if(l.j==f&&(a.referrer=l.m,(c=b[l.a])&&c.u==l.tabId))break}var m;Q(f,l=T());f!=a.url&&Q(a.url,m=T());U(this.tb,this,a,l,m);return a.lb=!0}return this.tb(a)};
n.tb=function(a,b,c){var e=Date.parse(a.startTime)||Date.now();e=[a.id,0,e.toFixed(),0,a.R,2];var d={};d[6]=$b(a.finalUrl);d[4]=a.pa;d[103]=a.totalBytes||null;d[100]=a.filename||null;d[127]=a.mime||null;d[8]=a.da?2048:0;d[50]=a.referrer||null;d[51]=R(b);d[54]=navigator.userAgent;d[122]=this.s;a.finalUrl!=a.url&&(d[17]=$b(a.url),d[56]=R(c));return!!P(this,13,1,129,e,d)||kc(this,a.id)};
function kc(a,b,c){var e=a.ra[b];if(e){if(c)return browser.downloads.cancel(b,O),!0;e.lb&&(e.lb=!1,e.Lc());browser.downloads.resume(b,O);delete a.ra[b]}return!1}n.lc=function(a,b,c,e,d,f){this.Ia(a,b,c,e);a=[b,a.tabId,a.c,a.ha,a.O];b={};b[132]=e;b[133]=d;b[134]=f;P(this,23,2,0,a,b)};
n.W=N[N.length]=function lc(a,b,c){if(4294967295==a)this.m=null,c=!0;else{var d=this.g[a];if(d){c=d.a;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:d.a=3;H.setTimeout(lc.bind(this),1E3,a,!1,!0);return}d.a=0;c=!0}}c&&P(this,8,1,32,[a])};
n.Sc=function(a,b,c,e,d,f,h,k,g,l){var m=a.tabId,p=a.a,q=this.b[p],t=this.i[m];if(b){var u=Ub(this,b);if(u=u&&u.H){if(!c&&a.i){var C=this.a[a.b];if(C)return C.postMessage([15,b,null,u[6],u[17],u[50],u[31],u[133],u[134]])}var w,v;b={};if(!e){if(!c||null==d){if(!a.B){c=a.na;f="iframe";h=a.j;var A=!!c}if(!A){c=m;f=h=null;var K=!0}}a=this.Ia(a,c,f,h);q=m==q.u&&!q.L&&(K||A||d)&&!t;!q||K||a.a||H.setTimeout(this.aa,3E3,p);var E=2;a.a=q?1:2;var S=(q?128:64)|(K?512:0);!k&&(w=this.a[m])&&(k=w.l)}k&&(b[101]=
k,b[128]=g);l&&(b[137]=l);!E||K||t||(v=this.Ea.bind(this,c,d));W(this,u,E||1,S||0,p,m,c,b,v)}}else e?(this.W(c,!0),delete this.g[c]):m!=q.u||q.L||t||(d?this.Ea(c,d,!0):mc(this,c))};function nc(a,b){var c=a.b[b];if(c&&c.ea){var e=c.b,d=c.a;P(a,7,2,c.L?128:c.o?256:c.g?512:0,[b,Math.round((c.h+e)*d),Math.round((c.G+e)*d),Math.round((c.width-e-c.s)*d),Math.round((c.height-e)*d)])}}
n.Ea=function(a,b,c){var e=this.g[a];if(e&&e.a){var d=e.port,f,h=256;2==e.a&&(null==c&&(f=this.b[d.a])&&(c=d.tabId==f.u&&!f.L),c?(h|=128,e.a=1):h|=64);(c=e.fa)&&!b&&(b=d.f);if(b){var k=b[0];var g=b[1];var l=b[2]||k+1;var m=b[3]||g+1;var p=b[4];if(b=!c&&d.f)k+=b[0],g+=b[1],l=Math.min(l+b[0],b[2]),m=Math.min(m+b[1],b[3]);if(d=this.a[d.tabId])var q=d.o}P(this,9,1,h,[a,k,g,l,m,p,q])}};
n.aa=function(a){var b=this.i,c=this.a,e=this.b,d=a?[e[a]]:V(e);a=[];e={};for(var f of d)!f||f.L||f.$||b[f.u]||a.push(f.u);if(a.length)for(var h of V(this.g))h.a&&(b=h.port,f=b.tabId,a.includes(f)&&((f=b.B?b:c[f])&&f.update&&(f.update=!1,f.postMessage([14,!1])),h.b?b.B?b.postMessage([15,null,h.id]):hc(this,b,null,e):this.Ea(h.id,null,!0)))};function oc(a,b){var c=a.b,e;if(b=null==b?V(c):(e=c[b])?[e]:null)for(e of b)Cb(a,e.u,void 0)}
function Cb(a,b,c,e){e=0!=e;var d=c?0:2;c=c?32:64;var f=a.g,h;for(h in f){var k=f[h];k.a&&k.port.tabId==b&&k.a!=d&&(e||k.b)&&(k.a=d,P(a,8,1,c,[h]))}}function mc(a,b){var c=a.g[b];c&&1==c.a&&(c.a=2,P(a,8,1,64,[b]))}function pc(a,b,c,e){var d=a.Ha,f=(d&b)!=((c?255:128)&b);a.Ha=c?d|=b:d&=~b;f&&(c=a.c[-32],b=a.c[-33],c=a.Ka=0!=c&&(d&c)==c,d=a.Qa=0!=b&&(d&b)==b,a.ob=(c||d)&&e||null)}
n.$a=N[N.length]=function qc(a,b,c,e,d){var h=this.b[a];if(h)if(h.$?e&&(H.clearTimeout(h.$),h.$=null):e||(e=-1),0<=e)h.i|=b,h.l|=c,e&&(h.$=H.setTimeout(qc.bind(this),e,a));else{b|=h.i;c|=h.l;h.i=h.l=h.$=null;if(b){for(var k of V(this.h))k.B&&k.a==a&&(k.update=!0);d?this.M(d):browser.windows.get(a,this.M);browser.tabs.query({windowId:a,active:!0},this.M)}if(c){if((a=this.b[a])&&!a.L&&!a.$&&(a=a.u,!this.i[a])){b=this.g;for(var g in b)c=b[g],c.a&&c.port.tabId==a&&1==c.a&&P(this,8,1,1152,[g])}}else this.aa(a)}};
n.M=N[N.length]=function rc(a,b){browser.runtime.lastError;a instanceof Array&&(a=a.shift());if(a){var e=a.windowId||a.id,d=this.b[e];if(d){var f=!a.windowId;if(f){var h=b?d.a=this.Na:d.a,k=d.g="minimized"==a.state,g=d.o="maximized"==a.state;k||(D?(d.width=Math.round(a.width/h),d.height=Math.round(a.height/h),d.c=Math.round(a.left/h),d.f=Math.round(a.top/h)):(d.width=a.width,d.height=a.height,d.c=a.left,d.f=a.top),k=d.L,a=d.L="fullscreen"==a.state,h=g&&-d.c,0<h&&16>=h&&h==-d.f&&(d.b=h),a==k||b||(a?
oc(this,e):this.aa(e)))}else{if(d.H&&Qa(a.url))return;a.active&&(d.u=a.id);a.width&&(d.D=a.width);a.height&&(d.v=a.height)}if(!d.g){h=d.width;k=d.D;g=d.height;a=d.v;var l=!F&&(k>h||a>g);if(l||!k||!a){f||l&&browser.windows.get(e,rc.bind(this));return}f=h-k;h=f/2;0<=h&&16>=h?(d.b=h,d.h=d.s=0):(h=d.b,F||ka?d.h=f-2*h:d.s=f-2*h);f=g-a-2*h;f>=(d.I?20:50)&&f<=ua&&(d.G=f);d.H=!0}b||nc(this,e);return d}}};function Bb(a,b){return a.i[b]?!0:(a=a.a[b])&&a.refresh?(a.refresh=!1,browser.tabs.reload(b),!0):!1}
n.Pc=function(a,b,c,e){a.j=b;a.m=c;a.refresh&&!e&&(a.refresh=!1);null==a.O&&this.kb(a);this.aa(a.a);a.B&&0<this.N&&sc(this)};n.Rc=function(a,b,c,e,d){a.l=b;a.o=d;a=[a.c,a.tabId,a.a,e,d];e={};e[110]=b;e[128]=c;P(this,21,1,0,a,e)};
n.Tc=function(a,b,c,e,d){var f=a.tabId,h=this.a[f+","+c];if(h){var k=h.f;h.na=e;if(h.f=d){var g=a.f;g&&(d[0]+=g[0],d[1]+=g[1],d[2]=Math.min(d[2]+g[0],g[2]),d[3]=Math.min(d[3]+g[1],g[3]));if(k&&k.join()!=d.join()){k=this.a;a=a.tabId+",";c=a+c;for(var l in k)l.startsWith(a)&&(g=k[l],g.b==c&&h.postMessage([16,b,g.O,g.na]))}}if(!this.i[f]){this.Ea(e,d);for(var m of V(this.g))m.port==h&&m.a&&m.b&&!m.fa&&h.postMessage([15,null,m.id])}}};
function hc(a,b,c,e){a=a.a;c=[16,c];for(var d=[b],f;f=a[b.b];b=f){if(e)if(e[b.id])break;else e[b.id]=!0;d.push(f)}for(f=d.pop();b=d.pop();f=b)e=b.na,c[2]=b.O,c[3]=e,c[4]=e?null:b.j,c[5]=e?null:b.Y,f.postMessage(c)}function ic(a,b,c){a=a.a;b+=",";var e=0,d;for(d in a)d.startsWith(b)&&(a[d].postMessage(c),e++);return e}
n.Ba=function(a,b){var c={file:"content.js",runAt:"document_start",matchAboutBlank:!0};!D&&b?c.frameId=b:c.allFrames=!0;if(a instanceof Array)for(;b=a.shift();)try{b.discarded||browser.tabs.executeScript(b.id,c,O)}catch(e){}else if(b=a)try{browser.tabs.executeScript(b.id||b,c,O)}catch(e){}};function tc(a,b,c,e){null==c&&(c=b.m==a.ja);c=17|(c?2048:1024)|(b.o?256:b.g?512:0);b=[b.m,b.ea,b.width,b.height,b.c,b.f,b.a];var d={};d[117]=e;P(a,6,2,c,b,d)}
n.Ib=N[N.length]=function uc(a,b,c){if(b){a={};for(var d of c)a[d.windowId]=d;for(var f of b)d=a[f.id],b=this.M(f,!0)||this.Bb(f,!0,d),tc(this,b,f.focused,f.title||d&&d.title)}else{if(!a){try{browser.windows.getAll({windowTypes:["normal","popup","app"]},b=T())}catch(h){browser.windows.getAll(b)}browser.tabs.query({active:!0},c=T());return U(uc,this,1,b,c)}if(D&&1==a&&c){b=fc();for(d of c)browser.windows.get(d.windowId,b[b.length]=T());return U(uc,this,2,b,c)}}};
n.Oc=N[N.length]=function vc(a,b){if(void 0===a)return wc("system.display",vc.bind(this));if(a){if(!b)return browser.system.display.getInfo(null,vc.bind(this,a));this.Hb=b[0].displayZoomFactor}};
n.mc=function(a){var b=a.sender.tab;if(b&&!(0>b.id)){a.name=a.name.split(":").shift();var c=a.id;null==c&&(c=a.id=this.Mc++);var e=b.id,d="top"==a.name;a.tabId=e;a.a=0>b.index?null:b.windowId;a.g=!0;a.h=!1;a.update=d;a.B=d;a.O=d?0:a.sender.frameId;a.s=0;a.j=a.sender.url||d&&b.url||null;a.Y=null;this.h[c]=a;d&&(this.a[e]=a);a.j&&(a.ha=Vb(this,(new URL(a.j)).hostname));a.onMessage.addListener(this.nc.bind(this,a));a.onDisconnect.addListener(this.Ca);this.kb(a)}};
n.Ca=function(a,b){browser.runtime.lastError;if(a.g){a.g=!1;var c=a.tabId+","+a.O,e=this.ma,d=this.g,f,h=this.sa,k=this.f,g,l;for(l in e)e[l].port===a&&delete e[l];for(l in d)if(f=d[l],f.port===a)this.W(l),delete d[l];for(var m in h)h[m]===a&&delete h[m];for(l in k)(g=k[l],g.port!==a||g.C)||delete k[l];this.ob===a&&pc(this,255,!1);delete this.h[a.id];delete this.a[c];a.B&&delete this.a[a.tabId];if(D&&!b)browser.tabs.executeScript(a.tabId,{code:"__idm_connect__ && __idm_connect__(); true;"},O);else for(l in a=
this.D,a)c==a[l].c&&delete a[l]}};
n.nc=function(a,b){var c=b[0];b[0]=a;switch(c){case 21:this.Pc.apply(this,b);break;case 24:this.Rc.apply(this,b);break;case 22:this.Tc.apply(this,b);break;case 23:this.Sc.apply(this,b);break;case 41:this.lc.apply(this,b);break;case 25:this.Ia.apply(this,b);break;case 26:yb(this,a.tabId,!0,!0,!1,a,b[1],b[2],b[3]);break;case 27:this.Ec.apply(this,b);break;case 28:this.W(4294967295);break;case 29:this.vb.apply(this,b);break;case 30:this.vb.apply(this,b);break;case 31:this.fc.apply(this,b);break;case 32:this.jc.apply(this,
b);break;case 39:this.hc.apply(this,b);break;case 33:this.ac.apply(this,b);break;case 34:this.ec.apply(this,b);break;case 35:this.ic.apply(this,b);break;case 36:this.Dc.apply(this,b);break;case 37:this.pc.apply(this,b)}};
n.xb=function(a){var b=a.type,c=a.m,e=a.flags,d=a.a,f;if(1==b){var h=d[0];if(f=this.wa[h])b=f.type,delete this.wa[h]}switch(b){case 3:0<=this.xa&&(this.xa=-1,this.eb());e=d[0];var k=d[5];f=d[6];c=d[4];var g=d[8];this.ba=e;this.rb=9>e;this.hb=10<=e;xc(this,f);yc(this,k,a);zc(this,!0);if(c||g)g=(c?c/96:1)*(g?g/100:1),this.Na=B&&1.245>g?1:g,this.Ib(),B&&this.Hb&&this.Oc();Wb(this);break;case 4:g=this.c;this.o=!!(d[3]&2147483648);this.Ja=!!(d[3]&1073741824);yc(this,d[2],a);zc(this);e&2048&&(H.idm=this);
g[-6]=0<(e&64);g[-10]=0<(e&1024)||Ma;g[-5]=0<(e&32);g[-1]=0<(e&2);g[-8]=0<(e&256)||2>c;g[-9]=0<(e&512)||2>c;g[-32]=d[0];g[-33]=d[1];g[12]=a[12];g[17]=a[17];X(g,a,1);X(g,a,2);X(g,a,3);X(g,a,4);X(g,a,10);X(g,a,9,2);X(g,a,11,2);X(g,a,20);X(g,a,21,1);Ac(g,a,19);Ac(g,a,18,1,1);(this.I||this.ib)&&Ab(this);break;case 18:e=d[0];g=d[1];d=hb[g?-g:e];if(!d)break;g=this.ca[e]={};f=d[2];g.ha=e;g.Pb=d[0];g.Mb=d[1];for(k in a)(k=parseInt(k))&&(102==k||110<k&&150>k)&&(g[k]=f.includes(k)?RegExp(a[k]):a[k]);for(k of f)g[k]||
(g[k]=Aa);d=this.ca.map(Bc(102)).filter(aa);this.nb=RegExp("^https?://(?:"+d.join("|")+")","i");X(g,a,101,2);break;case 5:a=d[0];g=d[1];Cc(this,a,e,g);break;case 6:if(e&4)break;a=f.a[0];k=d[1];g=d[2];Cc(this,a,e,g,k);break;case 8:a=d[0];g=e&32;if(4294967295==a)ic(this,this.m,[13,!1]),this.m=null;else if(a=this.g[a])a.a=g?0:2;break;case 11:a=d[0];4294967295==a&&(yb(this,this.m,!0,!0),this.m=null);break;case 12:try{var l=a.a[5];g=4==l?2:3;if(1==l||2==l){if(Xb(this,a)){var m=a[4];if(this.c[3].test(m))1==
l?g=6:l=4;else if(this.c[-1]||this.c[4].test(m))g=6;a[8]|=256}if(3==g){var p=this.b[this.ja];p&&this.i[p.u]&&(g=1)}}if(4!=l)W(this,a,g);else if(!this.rb||a.a[6]||a.a[7]){switch(a.a[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}this.Fc(a)}else W(this,a,1)}catch(q){W(this,a,0)}break;case 13:a=f.a[0];e=f.a[5];d=d[1];k=3==d;if(3>=e)f.flags&128?kc(this,a,k):Y(this,a,k);else if(5==e)if(d){if(a=(e=this.f[a])&&e.oa){k=e.method;d=e.Z;f=e.requestHeaders;d&&((d=Dc(d,Z(f,
"Content-Type")))?d=new Blob(d):k="GET");a.timeout=1E4;a.onreadystatechange=this.oc.bind(this,a,e.id);a.open(k,e.url,!0);for(g of f)e=g.name,k=e.toLowerCase(),k.startsWith("x-idm-")||(Ra(k)&&(e="x-idm-"+e),a.setRequestHeader(e,g.value));a.send(d)}}else Ec(this,a);break;case 20:g=a[123];d=!g;a=[a.f];e={};F&&(k=this.ka)&&(e[122]=k,d||(d=k.substr(2).split(";",1).shift()==g));e[121]=this.s;P(this,1,2,d?2:4,a,e);break;case 24:this.Gc(a);break;case 22:this.Jb(d[0],d[1],a[131],a[130]);break;case 100:e&1&&
P(this,100,1,0,[a.f],a);break;default:e&1&&P(this,1,2,0,[a.f])}};n.Jb=N[N.length]=function Fc(a,b,c,e,d){if(!D&&null==va){if(void 0===d)return wc("notifications",Fc.bind(this,a,b,c,e));va=d||!1}va&&(browser.notifications.create(a.toString(),{type:"basic",title:e||"",message:c,iconUrl:"images/logo48.png"},O),b&&H.setTimeout(browser.notifications.clear,1E3*b,a.toString(),O))};
n.Gc=N[N.length]=function Gc(a,b,c){if(!b)return c=!!(a.flags&16),Q(a[6],Gc.bind(this,a,!0),c);b=browser.runtime.lastError||!c;a=[a.f,c?c.length:0];var d={};c&&(d[51]=R(c));P(this,1,2,b?4:2,a,d)};
n.Fc=N[N.length]=function Hc(a,b,c,e){try{var f=a.c||a.a[2],h=a.a[8],k=this.g[h];if(b)if(c)var g=this.h[c];else{if(e){var l=this.b[e.id];l&&(g=this.a[l.u])}}else if(k&&k.port)g=k.port;else if(f in this.h)g=this.h[f];else if(f=this.Ob(a,c=T()))g=this.h[f];else return browser.windows.getLastFocused(e=T()),U(Hc,this,a,!0,c,e);if(g)a.c=g.id;else return W(this,a,0);l=this.b[g.a];if(!l||!l.ea)return W(this,a,1);var m=this.a[g.tabId];m&&m.update&&(m.update=!1,m.postMessage([14,!0]));var p=Tb(this),q=[15,
p.a,h];p.H=a;h||q.push(a[6],a[17],a[50],a[31],a[133],a[134]);g.B||hc(this,g,p.a);g.postMessage(q)}catch(t){return W(this,a,0)}};function W(a,b,c,e,d,f,h,k,g){if(-1!=c){k||(k={});k[8]=b[8];a=l.bind(a,e|(0==c?4:2),[b.f,c,d,h,f,-1],k,g);b.flags&32&&(3==c||2==c)?Q(b[6],a,!!(b.flags&16)):a();function l(m,p,q,t,u){browser.runtime.lastError;u&&(p[5]=u.length,q[51]=R(u));P(this,1,2,m,p,q)&&t&&t()}}}n.kc=function(a){Pb(this,a).a=!0;F&&browser.windows.get(a.windowId,this.M)};
n.yb=function(a,b){var c=a.tabId,e=a.frameId,d=a.url,f=a.transitionType,h=f?f.endsWith("_subframe"):D&&0<e,k=this.D[c+","+e];this.K!=c||Qa(d)||(this.K=null);!h&&this.i[c]&&(k?(f=k.h,f=!(d&&f&&(new URL(d)).hostname==(new URL(f)).hostname)):f=!0,wb(this,f,c));k&&(k.h=d);if(f=this.a[c+","+e])if(this.m&&(a=this.b[f.a])&&a.u==this.m&&this.W(4294967295),b){a:{b=f.j;c=new URL(b);e=new URL(d);if(c.origin==e.origin&&c.pathname==e.pathname)switch(Vb(this,c.hostname)){case 1:if("/watch"==c.pathname&&c.a("v")==
e.a("v")){b=!0;break a}break;case 4:if((c.pathname.startsWith("/p/")||c.pathname.startsWith("/reel/"))&&c.a("img_index")==e.a("img_index")){b=!0;break a}}b=d==b}if(!b){b=this.g;var g,l;for(l in b)if(g=b[l],g.port===f)2==f.ha||4==f.ha?mc(this,l):(this.W(l),delete b[l]);f.s++;f.j=d;f.B&&(f.update=!0);f.postMessage([17,!0])}}else this.Ca(f,!0),h&&"about:blank"==f.j&&this.Ba(c,e);else h&&"about:blank"==d?(Pb(this,a),this.Ba(c,e)):k&&k.a&&(k.j||!b)?k.a=!1:F&&browser.tabs.get(c,this.M)};
n.bc=function(a){return this.yb(a,!0)};
n.Bb=function(a,b,c){var e=a.id;c={m:e,width:a.width,height:a.height,c:a.left,f:a.top,a:this.Na,b:8,G:ta,h:0,s:0,I:"popup"==a.type||"app"==a.type,L:"fullscreen"==a.state,o:"maximized"==a.state,g:"minimized"==a.state,u:c&&c.id,v:c&&c.height,D:c&&c.width,H:!F,ea:null,$:null};Object.setPrototypeOf(c,rb.prototype);this.b[e]=c;a.focused&&(this.ja=e);b?(browser.tabs.query({windowId:e,active:!0},this.M),browser.tabs.query({windowId:e,url:L},this.Qc),browser.tabs.query({windowId:e,url:L},this.Ba)):F&&this.Sa==
e&&(this.Sa=null,browser.tabs.query({windowId:e,active:!0},this.M));return c};n.Qc=function(a){for(var b of a)Pb(this,0,!0,b.id,b.url)};n.Cb=function(a){P(this,5,1,32,[a]);delete this.b[a];this.J==a&&zb(this)};n.Cc=function(a){if(0<a){this.J&&browser.windows.update(this.J,{drawAttention:!0});var b=this.b[a];b&&(this.ja=a,b.ea||tc(this,b,!0),browser.windows.onBoundsChanged||browser.windows.get(a,this.M),Bb(this,b.u),D&&this.$a(a,!1,!0,500))}else this.ja=null};
n.Bc=function(a){this.$a(a.id,!0,!1,-1,a)};function Cc(a,b,c,e,d){var f=a.b[b];f?(e&&(f.a=e),d&&(f.ea=d),e=!!(c&128),f.L!=e&&(f.L=e)&&oc(a,b),(d||c&4096)&&nc(a,b)):a.Cb(b)}n.uc=function(a,b,c){var e=c.active;c=c.windowId;var d=e&&this.b[c];d&&(d.ea||tc(this,d));"complete"==b.status&&(a=this.a[a])&&!a.h&&(a.h=!0,e&&this.aa(c))};
n.tc=function(a){var b=this.a,c=this.D,e=a+",";this.K==a&&(this.K=null);var d=b[a];d&&this.Ca(d,!0);for(var f in b)f.startsWith(e)&&this.Ca(b[f],!0);for(var h in c)h.startsWith(e)&&delete c[h];delete this.i[a]};
n.rc=function(a){var b=a.tabId;a=a.windowId;this.Ha=0;this.m&&this.W(4294967295);var c=this.b[a];c?(Cb(this,c.u),c.u=b,(c=this.K)&&b!=c&&(this.J?browser.windows.update(this.J,{drawAttention:!0}):this.l&&this.I&&(this.K=null,H.setTimeout(browser.tabs.remove,250,c))),browser.tabs.get(b,this.M),Bb(this,b)||this.aa(a)):F&&(this.Sa=a)};n.sc=function(a,b){b=b.newWindowId;for(var c of V(this.h))c.tabId==a&&(c.a=b);Cb(this,a,!0)};n.dc=function(a){this.J&&"idle"==a&&browser.windows.update(this.J,{focused:!0})};
n.vb=function(a,b,c){if(a.B){var e=a.tabId;a=a.a;var d=this.b[a];this.m&&this.W(4294967295);if(d&&d.u==e){var f=!1;b&&(d.D=b,f=!0);c&&(d.v=c,f=!0);Cb(this,e,!1,f);this.$a(a,f,!1,500)}}else a.na&&(b=this.a[a.b])&&b.postMessage([16,null,a.O,a.na])};n.fc=function(a,b,c){(b=ib[b])&&pc(this,b,c,a)};n.jc=function(a,b,c){0==b&&pc(this,128,c,a)};n.hc=function(a,b,c,e){this.La=a.id;a.Sb=b;a.cb=c;a.Tb=e};n.ac=function(){pc(this,255,!1)};
n.ec=function(a,b,c,e){var d=a.c;d&&(a=32,c=[d,null==c?(a|=16,-2):c],d={},d[110]=b,d[115]=e,P(this,16,1,a,c,d))};n.Dc=function(a,b,c){if(a=this.f[b]){b=[a.id,0];var e={};e[115]=c;P(this,16,1,48,b,e);a.Aa=!1;a.mb&&Y(this,a)}};n.pc=function(a,b,c,e){P(this,19,2,0,[b,c,a.tabId,a.c],e)};function Ec(a,b){if(b=a.f[b]){var c=b.oa;b.Aa=!1;b.oa=null;b.mb&&Y(a,b);c&&c.abort()}}n.oc=function(a,b){if(4==a.readyState){var c=[b,0],e={};200==a.status&&(e[115]=a.response);P(this,16,1,48,c,e);Ec(this,b)}};
function Ic(a,b){var c=a.c;if(b.Da||a.i[b.tabId]||!c[-6])return 1;if(b.da)return 6;if(b.V&&c[-1])return 1;var e=b.Fa,d=b.ab=jc(e.pathname);return c[9].test(e.hostname)||c[19].test(e.href)?1:2==(b.R&7)&&(b.Wa||c[-10])?e.pathname.endsWith("/")||c[21].test(e.pathname)?1:c[1].test(d)||a.o&&!c[20].test(d)?4:1:6}
function Jc(a,b){var c=!b.P;if(b.da&&c)return 3;var e=a.c,d=e[18],f=e[1],h=b.Fa,k=b.ab,g=b.pa||(h.search?null:k),l=b.V,m=Ca.includes(b.type),p=!b.Wa,q=!m&&d.exec(h.href);if(q){var t=d.Uc,u=d.Vc,C=d.Wc,w=d.Xc;for(d=1;d<q.length;++d)if(q[d]){t=t[--d];if(null===t)break;q=0;if(t.includes("G")){var v=!0;q|="GET"==b.method}t.includes("P")&&(v=!0,q|="POST"==b.method);if(v&&!q)break;v=t.includes("V")|t.includes("A")|t.includes("C");t.includes("H")&&(b.sb=!0);if((v?b.sb:l?!t.includes("S"):t.includes("X"))||
p&&t.includes("D"))return 1;if(q=w[d]){q=q.exec(h.href);if(!q)break;h=u[d];if(u=h.F){var A=!0;var K=q[u]}if(u=h.T){A=!0;var E=q[u]}}E||(E=jc(K)||t.includes("T")&&(A=!0,k)||C[d]);if(v)return E&&(b.ab=E),l||(b.V=!0),b.P=!0,6;if(c&&(E?f.test(E):!A))return b.Za=16777216,4;break}}if(!c)return 6;if(g&&(m&&e[2].test(g)||l&&e[4].test(g)))return 1;if((F||a.U)&&(b.Wa||e[-10])){if(l&&e[3].test(g))return 6;if((!l||a.o)&&g&&f.test(g))return b.Za=8,4}return 6}
function Kc(a,b){if(b.Rb)return a.ga(6,b),6;var c=b.statusCode;if(200!=c&&206!=c&&304!=c)return 1;var e=Z(b.responseHeaders,"Content-Type"),d=Z(b.responseHeaders,"Content-Disposition"),f=Lc(e).toLowerCase(),h="attachment"==Lc(d).toLowerCase();c=b.V;var k=b.fa;if(b.Qb=k&&!h&&"text/html"==f){if(b.C){var g=Qb(a,b);g&&(g.C=!0);a.ga(5,b)}return 1}if(c?b.Da:b.P)return 1;if(a.o&&k&&h)return 4;var l,m,p,q=a.c,t=b.Fa,u=t.hostname,C=t.pathname;d=(e=Mc(d,"filename")||Mc(e,"name"))&&jc(e);if(e){if(!d&&!c)return 1;
if(d&&(!c||5>=d.length)){b.fileName=e;var w=p=!0}}p||(e=C.split("/").pop(),(d=b.ab||jc(e))&&d.toLowerCase()==f.split("/").pop()&&(w=!0));if(!w){var v=q[10].test(f),A=kb[f];if(A)if(A=A.split("|"),d&&A.includes(d))w=!0;else if(c&&Ua(d))w=!0;else if(c?!v:!d){w=!0;var K=v;d=A[0]}!w&&d&&(h&&k?w=!0:v?w=K=!0:A||Ta(d)||(w=K=!0))}if(c){A=Vb(a,u);k=a.ca[A];v=C+t.search;switch(A){case 0:break;case 1:if(k[111].test(v)){var E=w=!0;d=null}else if(k[112].test(v))var S=!0;else if(k[115].test(v)&&"application/json"==
f)var oa=!0;else if(k[113].test(v)||k[114].test(v))var pa=!0;break;case 2:(u=k[111].exec(v))&&(Sa(f)||"text/html"==f)?(f=u[1]&&k[112].exec(b.port.j))&&u[1]!=f[1]||(pa=!0):k[114].test(v)?oa=!0:h&&"image"==b.type&&"MP4"==d&&(m=!0);break;case 3:"M4S"==d&&(w=!0);u==k[111]&&k[112].test(C)&&Sa(f)&&(pa=!0);break;case 4:k[111].test(v)&&Sa(f)&&(oa=!0);break;case 5:k[111].test(v)&&"text/html"==f&&(oa=!0);break;case 6:k[111].test(v)&&(pa=!0);break;default:k[111].test(C)&&(oa=!0)}w&&("M3U8"==d||"F4M"==d||a.hb&&
"MPD"==d?pa=!0:"F4F"==d&&(e.endsWith("Seg1-Frag1")||e.endsWith("Seg1-Frag2")||e.includes("Seg1-Frag2_"))&&(l=!0));"ASF"==d&&((f=Z(b.responseHeaders,"Content-Length"))&&102400>=parseInt(f)&&(m=!0),"DCLK-AdSvr"==Z(b.responseHeaders,"Server")&&(m=!0))}if(m)return 1;w&&(c&&q[3].test(d)?E=!0:c&&q[4].test(d)?b.P=!0:!b.P&&q[1].test(d)&&(g=!0));if(E){var Rb,Sb;if(b.sb)E=!1;else if(m=q[11])m.test(t.hostname)?E=!1:(Rb=a.a[b.tabId])&&(Sb=Rb.j)&&m.test((new URL(Sb)).hostname)&&(E=!1)}if(oa)S=b.Aa=!0;else if(pa||
l)"POST"!=b.method||b.Z?(a=new XMLHttpRequest,a.responseType=l?"blob":"text",b.oa=a,S=!0):S=!1;if(!g&&!E&&!S)return 1;w&&(b.pa=d);p&&(b.fileName=e);b.C|=S;b.Za=E||S?256:16|(c?4096:0)|(K?8388608:0);return g?4:E?2:5}
n.ga=N[N.length]=function Nc(a,b,c,e,d,f){var k=b.url,g=b.R||dc(k),l=1==(g&7),m=b.requestHeaders;if(l&&!m&&!e)if(d)f=R(f);else if(f=Z(m,"Cookie"),null==f)return Q(k,Nc.bind(this,a,b,c,e,!0)),!0;var p=b.id,q=b.port&&b.port.id;d=b.timeStamp;var t=c?y(c.timeStamp-d):null,u=b.Za,C=b.responseHeaders,w=b.Db,v=c&&c.ip;c=0;3==(v?v.length-v.replaceAll(".","").length:0)?u|=33554432:2<(v?v.length-v.replaceAll(":","").length:0)&&(u|=4194304);g&16&&(u|=2097152);"POST"==b.method&&(u|=512);4>a&&(F||e)&&(c|=1);b.C&&
b.oa&&(c|=1);b.C&&5!=a&&(c|=32);b.V&&(c|=16);b.Va&&(c|=8192);b.fa&&(c|=b.B?2048:4096);g=[p,q,d.toFixed(),b.statusCode,g&7,a,b.tabId,b.frameId];p={};p[6]=$b(k,l&&4>a,this);p[12]=b.statusLine;p[17]=b.Y;p[4]=b.pa;p[100]=b.fileName;p[127]=b.$c;p[8]=u;p[129]=t;p[122]=this.s;p[11]=Oc(m);p[13]=Oc(C);p[18]=Oc(w);b.Z&&(p[14]=Dc(b.Z,Z(m,"Content-Type")));b.Ya&&(p[19]=Dc(b.Ya,Z(w,"Content-Type")));if(!m){a=this.D;k=b.tabId+","+b.frameId;do k=(l=a[k])&&l.c,l=l&&l.j,"about:blank"==l&&(l=null);while(!l&&k);p[50]=
l;p[51]=f;p[54]=navigator.userAgent}F&&(p[122]=Mb(this,b.proxyInfo,Z(m,"Proxy-Authorization")),p[55]=Mb(this,b.Eb,Z(w,"Proxy-Authorization")));if(!b.Qb||!b.B)if(b=this.a[b.tabId])p[7]=b.j;16>this.ba&&(g[2]=y(d/1E3),g[3]=y(d%1E3*1E3));return!!P(this,13,1,c,g,p,e)};
n.qa=N[N.length]=function Pc(a,b,c,e,d){if(0==a)b.resolve=e,b.reject=d,Ob(this,b);else{this.N&&sc(this,!0);e=this.U?new XMLHttpRequest:null;d=this.ga(a,b,c,e);e&&(d=(e=d&&parseInt(e.getResponseHeader("x-idm-status")))?3==e:this.ga(a,b,c));if(d)return Na&&!c?void(b.Ua=!0):F?new Promise(Pc.bind(this,0,b,null)):Y(this,b,!0);b.P=!0}};
function Y(a,b,c){var e=a.f,d;if(!r(b))if(b=e[b])void 0;else return;var f=b.id;if(c){if(b.fa||b.Va){var h=0<b.statusCode||!b.requestHeaders,k=Qb(a,b);k&&k.a&&b.B?browser.tabs.remove(b.tabId):B&&h&&!b.Va?d={redirectUrl:"javascript:void(0)"}:D&&h?d={redirectUrl:Qc(b,k)}:Pa&&h&&(d={redirectUrl:a.S||Qc(b,k)})}d||(d={cancel:!0});b.Ua=!0}(a=b.resolve)&&void 0!==c&&(b.resolve=b.reject=null,a(d||{}));if(c=b.reject)b.resolve=b.reject=null,c();if(b.oa||b.Aa)return b.mb=!0,d;delete e[f];F&&delete e[b.Ga];D&&
delete e[b.requestId];b.gb&&delete e[b.gb];return d}n.vc=function(a){var b=new URL(a.url);if(b.search.startsWith("?d=")){var c=this.a[a.tabId];this.ia("idmreg:"+b.href.substr(b.protocol.length),null,c&&c.j);Y(this,a.requestId);(b=Qb(this,a))&&b.a&&"main_frame"==a.type&&browser.tabs.remove(a.tabId);return{redirectUrl:Ia+"register=1"}}};n.Wb=function(a){if(!(0>a.tabId||a.initiator==Ka||this.Ja||(D||Pa)&&a.url.startsWith(Ia)&&a.type.endsWith("_frame")||a.url.startsWith(Ja)&&"main_frame"==a.type))return{cancel:!0}};
n.Ab=function(a){var b=a.type,c=a.tabId,e=a.frameId;if(!ra||Da.includes(b))if(!(0>c&&0==e)||F&&a.originUrl!=La){var d=a.url,f=a.method,h=dc(d);if(h&&("GET"==f||"POST"==f)&&d!=this.S){var k=a.id=D?String(this.Nc++):a.requestId,g=this.f[k],l=this.Qa,m="POST"==f,p="image"==b,q=B&&"other"==b,t=!q&&0>c&&(F||0>e),u=0<c&&b.endsWith("_frame"),C=t?null:this.a[c+","+e];if(C||u||t||q||g){F&&m&&g&&ab(g.statusCode)&&(f=a.method="GET",m=!1);u&&Pb(this,a,!1);if(!l&&m&&a.requestBody){m=a.requestBody;var w=m.raw;
if(w)for(var v=0;v<w.length&&(w[v].bytes||(w=null));v++);if(!(w||m.formData||B&&m.error))return}if((m=this.La)&&(w=C?C.id==m&&C:this.h[m])&&d==w.cb){q=w.Sb;if(m=w.Tb)a.fileName=m,a.pa=jc(m);C||(C=w);this.La=null}m=new URL(d);m.hash="";a.Fa=m;a.R=h;a.da=this.Ka;a.Da=l;a.B=u&&"main_frame"==b;a.fa=u;a.Va=q;a.Lb=t;a.V=t||J.includes(b);a.P=p;a.C=this.nb.test(d);a.Z=a.requestBody;a.port=C;a.Wa=h&8||(F?a.proxyInfo&&"https"==a.proxyInfo.type:this.za[h]);0>c&&(a.tabId=null);0>e&&(a.frameId=null);if(g)a.id=
g.id,a.port=C=g.port,a.da=g.da,a.Da=g.Da,a.Y=g.Y||g.url,a.Db=g.Db||g.requestHeaders,a.Ya=g.Ya||g.Z,F&&(a.Eb=g.Eb||g.proxyInfo);else if(F&&t)for(var A of V(this.f))if(A.Yc&&!A.Ga&&d==A.url&&b==A.type&&f==A.method){a=A;a.Ga=k;break}if(a.V&&!p){b=this.sa;c=b.Hc;e=c.indexOf(d);if(0<=e)c.splice(e,1);else for(;30<=c.length;)delete b[c.shift()];b[d]=C;c.push(d)}switch(a.action=Ic(this,a)){case 1:a.P=!0;case 6:Ob(this,a);break;case 4:return this.qa(1,a)}}}}};
n.xc=function(a){var b=this.f[a.requestId];if(b){var c=b.requestHeaders=a.requestHeaders;b.timeStamp=a.timeStamp;if(!b.Ua){if(b.Lb&&!b.port&&(a=Z(c,"Referer")))for(var e of V(this.h))if(e.j==a){b.port=e;break}F&&b.proxyInfo&&Mb(this,b.proxyInfo,Z(c,"Proxy-Authorization"),!0);e=b.Fa;if(!("POST"!=b.method||b.Z&&!(b.Z.error&&0<Z(c,"Content-Length"))||D&&1==Vb(this,e.hostname)&&this.ca[1][115].test(e.pathname+e.search)))return Y(this,b);switch(b.action=Jc(this,b)){case 1:b.P=!0;break;case 4:return this.qa(1,
b);case 3:return this.qa(3,b)}if(b.port&&b.port.C&&"xmlhttprequest"==b.type)for(e=0;e<c.length;e++){a=c[e];var d;if("accept"==a.name.toLowerCase()&&(d=Xa(a.value))){var f=b.gb=d[3];this.f[f]=b;d[1]||d[4]?a.value=d[1]+(d[4]&&d[2]||"")+d[4]:c.splice(e--,1);return{requestHeaders:c}}}}}else if(0>a.tabId&&"xmlhttprequest"==a.type&&(a.initiator?a.initiator==Ka:a.originUrl?a.originUrl==La:1)){b=a.requestHeaders;c={};d=!1;for(e=0;e<b.length;e++)a=b[e],f=a.name.toLowerCase(),f.startsWith("x-idm-")?c[f.substr(6)]=
d=!0:"origin"==f&&a.value==Ka&&(c[f]=d=!0);if(d){for(e=0;e<b.length;e++)a=b[e],f=a.name.toLowerCase(),c[f]?b.splice(e--,1):f.startsWith("x-idm-")&&(a.name=a.name.substr(6));return{requestHeaders:b}}}};n.wc=function(a){if(!a.statusCode&&a.redirectUrl==a.url){a=a.requestId;var b=this.f[a],c=b&&Qb(this,b);c&&!b.statusCode&&c.f==a&&(b.Yc=!0)}};
n.zc=function(a){var b=this.f[a.requestId];if(b){var c=b.statusLine=a.statusLine,e=b.statusCode=a.statusCode||parseInt(c.split(" ",2).pop());if(b.Ua||204==e&&c.includes(" IDM "))return Y(this,b,!0);c=b.responseHeaders=a.responseHeaders;b.Rb=$a(e);if("image"==b.type&&(e=Z(c,"Content-Type"))&&e.toLowerCase().startsWith("image"))return Y(this,b);"quic"==Z(c,"Client-Protocol")?b.R|=16:(e=Z(c,"Alternate-Protocol"))&&e.endsWith(":quic,p=0")&&"chunked"!=Z(c,"Transfer-Encoding")&&(b.R|=16);switch(b.action=
Kc(this,b)){case 1:return Y(this,b);case 4:return this.qa(2,b,a);case 3:return this.qa(3,b,a)}if(b.Aa)return c||(c=[]),c.push({name:"x-idm-request-id",value:b.id.toString()}),{responseHeaders:c}}};n.Ac=function(a){var b=this.f[a.requestId];if(a.type.endsWith("_frame")&&(200==a.statusCode||304==a.statusCode)){var c=Qb(this,a);c&&(c.j=a.url,c.Y=c.i)}b&&(2==b.action?this.ga(4,b,a):5==b.action&&this.ga(5,b,a),Y(this,b))};n.yc=function(a){Y(this,a.requestId)};
n.Ic=N[N.length]=function Rc(a,b,c,e){if(a){this.Fb=b.version;this.va=b.silent;this.jb=e;F&&(this.I=!!b.consent);b=b.client;if(c)for(var f of c)switch(f.name){case "idmwebext_cid":var h=parseInt(f.value);break;case "idmmzcc3_uri":this.ib=f.value==Ka}xc(this,null,b,h);this.Pa()}else c={url:I.homepage_url},qa&&(c.firstPartyDomain=null),browser.storage.local.get(null,b=T()),browser.cookies.getAll(c,c=T()),(F?1124073472<=G:D?1073741824<=G:1)&&browser.extension.isAllowedIncognitoAccess(e=T()),U(Rc,this,
!0,b,c,e)};function xc(a,b,c,e){a.ba&&92>a.ba?10<a.H&&(browser.storage.local.remove("client"),browser.cookies.remove({url:I.homepage_url,name:"idmwebext_cid"})):(b||(b=c||e))&&b!=a.H&&(a.H=b,c||browser.storage.local.set({client:b}),e||browser.cookies.set({url:I.homepage_url,name:"idmwebext_cid",value:String(b),expirationDate:2147483647}))}
function Wb(a){function b(l){l&&(this.K=l.id)}a.K&&(browser.tabs.remove(a.K),a.K=null);if(a.Gb||!a.I){var c=!a.l,e=!a.jb,d=!a.I,f=a.Ma,h=a.ya,k=a.Fb,g=a.Ta;if(c){if(a.ua&&a.va)return}else a.Gb=!1,g!=k&&(g&&browser.storage.local.set({version:g}),F&&browser.cookies.set({url:I.homepage_url,name:"idmmzcc3_uri",value:Ka,expirationDate:2147483647})),a.va&&(a.va=!1,browser.storage.local.set({silent:!1}));if(null!=k&&(d=!1,a.I=!0,g!=k?h&&k&&!f&&!d:!d))return;g=Ja+"current="+escape(g);k&&(g+="&previous="+
escape(k));h&&(g+="&manager="+(h?[h>>24&255,h>>16&255,h>>8&255,h&255].join("."):""));c&&(g+="&error=1");e&&(g+="&incognito=1");f&&(g+="&update=1");d&&(g+="&consent=1");F&&(g+="&mzffox=1");ka&&(g+="&opera=1");if(D||ja)g+="&msedge=1";if(d&&!c){browser.idle&&a.A(5,browser.idle.onStateChanged,a.dc)&&browser.idle.setDetectionInterval(15);browser.windows.create({type:"popup",width:Math.min(Math.round(.85*screen.availWidth),1100),height:Math.min(Math.round(.85*screen.availHeight),900),url:g},l.bind(a));
function l(m){m&&m.id?(this.J=m.id,this.K=m.tabs[0].id,wb(this,!1,null,!0)):zb(this)}}else browser.tabs.create({url:g},b.bind(a))}}function yc(a,b,c){null==b&&(b=(b=Za(c[13]))?b[1]<<24|b[2]<<16|b[3]<<8:0);a.ya=b||0}function zc(a,b){var c=a.Ma=103089920>a.ya,e=103219200>a.ya;c?a.N=null:a.N=e?6E4*y(120*z()+60)*(b?1:2)+Date.now():-1}
function sc(a,b){if(b||a.N<Date.now()){0<a.N&&(a.N=6E4*y(240*z()+120)+Date.now());var c="xup://"+z().toString(36).substr(2);b?a.ia(c):H.setTimeout(a.ia,y(5E3*z()+5E3),c)}}function gc(a,b){b=browser.i18n.getMessage(b);F?browser.tabs.executeScript(a,{code:'window.alert(unescape("'+escape(b)+'")); true;'},O):window.alert(b)}n.A=function(a,b,c){if(null==b)return!1;var e=da(arguments);if(F||D)e[2]=function(){return c.apply(null,arguments)};this.bb.push(e);b.addListener.apply(b,e.slice(2));return!0};
n.Oa=function(){for(var a=arguments.length?da(arguments):null,b=this.bb,c=0;c<b.length;c++)if(!a||a.includes(b[c][0])){var e=b.splice(c--,1).pop(),d=e.splice(0,2).pop();D&&e.splice(1);d.removeListener.apply(d,e)}};function T(){function a(b){browser.runtime.lastError;a.a?a.a(b):a.c=b;a.b=!0}return a}T.prototype=Object.create(Function.prototype);function fc(){var a=[];Object.setPrototypeOf(a,fc.prototype);return a}fc.prototype=Object.create(Array.prototype);
function U(a,b,c){if(this instanceof U){c instanceof Array||(c=fa(arguments,2));for(var e=0,d=0,f=Function.prototype.bind.bind(this.g,this),h=0;h<c.length;h++){var k=c[h];if(k instanceof Function)k.b?(c[h]=k.c,d++):(k.a=f(h,null),e++);else if(k instanceof fc)for(var g=0;g<k.length;g++){var l=k[g];l.b?(k[g]=l.c,d++):(l.a=f(h,g),e++)}}e?(this.c=a,this.f=b,this.a=c,this.b=e):a.apply(b,c)}else return(new U(a,b,fa(arguments,2))).b}
U.prototype.g=function(a,b,c){var e=this.a;if(null===b)for(var d=2;d<arguments.length;d++)e[a++]=arguments[d];else e[a][b]=c;0==--this.b&&(this.c.apply(this.f,e),delete this.c,delete this.f,delete this.a)};function Jb(a){return browser.i18n.getMessage(a)||a}function $b(a,b,c){var e=a.lastIndexOf("#");e>a.indexOf("?")&&"!"!=a[e+1]&&(a=a.substr(0,e));b&&!Va(a)&&(c.Ma?a="idm0x00000001"+a:a.startsWith("xup")&&(a="idm0x00000002"+a.slice(3)));return a}
function Qc(a,b){var c=a.port;b=b&&!b.g;var e=new URL(c&&c.j||a.url);D&&(c&&a.url==c.cb||(b=!1));return Ia+(b?"back=1":"host="+e.hostname)}function dc(a,b){a=a.split(":",1).shift().toLowerCase();a=jb[a]||0;return b?a&7:a}function jc(a){return(a=Ya(a))?a[1].toUpperCase():""}function Q(a,b,c){if(D&&a.startsWith("ftp:"))return b([]);a={url:a};c&&(a.session=!1);qa&&(a.firstPartyDomain=null);browser.cookies.getAll(a,b)}
function R(a){if(!r(a))return a;var b=[],c;for(c of a)b.length&&b.push("; "),b.push(c.name,"=",c.value);return b.join("")}function Oc(a){if(!a||!a.length)return null;var b=[],c;for(c of a)b.push(c.name,": "),null!=c.value?b.push(c.value):c.binaryValue&&b.push(new Uint8Array(c.binaryValue)),b.push("\r\n");return b}
function Z(a,b){if(!a)return null;b=b.toLowerCase();for(var c of a)if(c.name.toLowerCase()==b){if(null!=c.value)return c.value;if(c.binaryValue)return String.fromCharCode.apply(null,c.binaryValue)}return null}
function Mc(a,b){if(!a)return null;a=a.split(";");for(b=b.toLowerCase();a.length;){var c=a.shift(),e=c.indexOf("=");if(0<e){var d=c.slice(0,e).trim().toLowerCase(),f=d.endsWith("*");if(f)d=d.slice(0,-1).trimRight();else if(k)continue;if(d==b){c=c.substr(e+1).trim();e=c.length-1;if('"'==c[0]?'"'==c[e]:"'"==c[0]&&"'"==c[e])c=c.slice(1,e);if(f&&c.includes("'")){if(c=c.split("'",3),f=c.shift().toLowerCase(),(e="utf-8"==f||"utf8"==f)||!k){var h=unescape(c.pop());var k=f;if(e)break}}else h=unescape(c)}}else 0>
e&&null==h&&c.trim().toLowerCase()==b&&(h="")}return h}function Lc(a){const b=/[;,]/;return a&&(a=a.split(b,1).shift().trim())&&!a.includes("=")&&unescape(a)||""}
function Dc(a,b){var c,e=[];if(c=a.raw)for(var d of c)if(d.bytes)e.push(d.bytes);else return null;else if(a=a.formData)if((c=Lc(b).toLowerCase())&&"application/x-www-form-urlencoded"!=c)if("multipart/form-data"==c){(b=Mc(b,"boundary"))||(b="----WebKitFormBoundary"+z().toString(36).substr(2));for(f in a)for(h of a[f])e.push("--",b,'\r\nContent-Disposition: form-data; name="',f,'"\r\n\r\n',h||"","\r\n");e.push("--",b,"--\r\n")}else return null;else for(var f in a){b=encodeURIComponent(f).replaceAll("%20",
"+");for(var h of a[f])h=h instanceof ArrayBuffer?escape(Sc(h)):null==h?"":encodeURIComponent(h),e.length&&e.push("&"),e.push(b,"=",h&&h.replaceAll("%20","+"))}else return null;return e.length?e:null}function mb(a){for(var b=a.length,c=b,e=0;e<c;){var d=a.charCodeAt(e++);128<=d&&(2048<=d?(b+=2,d-55296&56320||e++):b++)}return b}
function Tc(a,b,c,e,d){browser.runtime.lastError;if(!a){ja&&Uc();D||browser.runtime.getPlatformInfo(b=T());navigator.userAgentData?navigator.userAgentData.getHighEntropyValues(["fullVersionList","uaFullVersion"]).then(c=T()):browser.runtime.getBrowserInfo&&browser.runtime.getBrowserInfo(c=T());try{browser.privacy&&browser.privacy.websites.firstPartyIsolate.get({},e=T())}catch(l){e=null}B&&browser.management.get("clhiejnehegdfknplplojohghjaklbae",d=T());return U(Tc,null,!0,b,c,e,d)}if(b&&"win"!=b.os)return Db(!1);
a=navigator.userAgent;var f=a.match(/\s(?!(?:Chrome|Firefox|Gecko|Safari)\/)([A-Z]\w+)(?:\/(\d+(?:\.\d+){0,3}))?\b(?!.*\)\s+\S)/),h=a.match(/\s(Chrome|Firefox)\/(\d+(?:\.\d+){0,3})\b/);a=h?h[1]:"UNKNOWN";b=f?f[1]:a;h=h&&h[2]||"0.0";f=f&&f[2]||h;F&&(a="Mozilla");B&&navigator.brave&&(b="Brave");B&&d&&(b="Epic",sa=!0);if(r(c)){if(d=c.uaFullVersion)f=d;if(d=c.fullVersionList)for(var k of d){if(d=k.version)switch(k.brand){case "Chromium":a="Chrome";parseInt(d)==parseInt(h)?h=d:(b="UNKNOWN",f=d);break;
case b:f=d}}else if(d=c.version)if(53<=parseInt(d)&&(h=d),d=c.name)b=d}d=h.split(/\D+/);G=d[0]<<24|d[1]<<22|d[2]<<8|d[3];ma=a+"/"+h;na=b+"/"+f;F&&r(e)&&(qa=e.value);F&&939524096>G&&(Pa=!0);c=browser.webRequest.ResourceType;if(c){if(c.MEDIA){Da.push("media");J.push("media");var g=!0}if(c.OBJECT_SUBREQUEST||(ra=F&&922746880>G))Da.push("object_subrequest"),J.push("object_subrequest")}B&&(g||J.push("other"));F&&922746880>G&&J.push("other");D&&(Da.push("fetch"),J.push("fetch"));new M;Vc(1,"debug.js");
Vc(2,"document.js")}function Uc(){var a="llbjbkhnmlidjebalopleeepgdfgcpec"==browser.runtime.id&&"ngpampappnmepgilojfohadhhmbhlaek";browser.management.get(a||"llbjbkhnmlidjebalopleeepgdfgcpec",function(b){browser.runtime.lastError;b&&b.enabled&&browser.management.setEnabled(a||browser.runtime.id,!1)})}
function Vc(a,b,c){c?4==c.readyState&&(gb[a]=btoa(c.responseText)):(c=new XMLHttpRequest,c.responseType="text",c.onreadystatechange=Vc.bind(null,a,b,c),c.open("GET",browser.runtime.getURL(b)),c.send())}
function X(a,b,c,e){if(b=b[c]||void 0)try{b=b.replace(/^\|+|\|+(?=\||$)/g,"").replace(/\./g,"\\."),b=1==e?b.replace(/\?/g,"[^/\\\\]").replace(/(^|[^*])\*(?!\*)/g,"$1[^/\\\\]*").replace(/\*\*/g,".*?"):b.replace(/\?/g,".").replace(/\*/g,".*?"),2==e&&(b=b.replace(/(^|\|)([^|]+?)~/g,"$1(?:$2\\.)?").replace(/(^|\|)~/g,"$1(?:.*?\\.)?")),b=RegExp("^(?:"+b+")$",1==e?"":"i")}catch(d){b=null}a[c]=b||Aa}
function Ac(a,b,c,e,d){b=b[c];var f=[],h=[],k=[],g=[];if(b)try{b=b.replace(/^\|+|\|+(?=\||$)|\*+(?=\*)/g,"").replace(/[.?+(){}[\]]/g,"\\$&").replace(/\*(?=[^:/|&]*:\/\/)/g,"\\w%%").replace(/(:\/\/[^:/]*?)~/g,"$1(?:\\b[^./]+\\.)?").replace(/\\\?(?=\||$)/g,"(?:$&.%%)?");if(e){for(var l=b.replace(/(^|\|)(?:([A-Z]+)?(?:#(\w+))?!)?[^|]+/g,"$1$2|$3").split("|");l.length;){var m=l.shift();f.push(Wa(m)?m:null);h.push(l.shift())}b=b.replace(/(^|\|)[\w#]+!/g,"$1")}if(d){l=b.replace(/(^|\|)(?:(?=[^|]+?<[A-Z]:.*?>)|[^|]+)/g,
"$1").split("|");m=/<([A-Z]):(.*?)>/g;for(var p={F:"[^/\\?#&;]%%",T:"[^/\\?#&;.]%%"},q,t=0;l.length;++t)if(q=l.shift()){for(var u={},C=["^"],w="",v,A=1;v=m.exec(q);++A)u[v[1]]=A++,w=RegExp.rightContext,C.push(RegExp.leftContext,"(",v[2].replace(/\*/g,p[v[1]]||".%%?"),")");C.push(w,"$");k[t]=u;g[t]=RegExp(C.join("").replace(/\*/g,".*?").replace(/%%/g,"*"))}b=b.replace(m,"(?:$2)")}b=b.replace(/\*/g,".*?").replace(/%%/g,"*");b=e||d?RegExp("^(?:("+b.replace(/\|/g,")|(")+"))$"):RegExp("^(?:"+b+")$")}catch(K){b=
null}a[c]=b||(b=/(?!)/);e&&(b.Uc=f,b.Wc=h);d&&(b.Vc=k,b.Xc=g)}function nb(a){return ia(a instanceof ArrayBuffer?new Uint8Array(a):a)}function bc(a){return r(a)?a.source.replaceAll("\\/","/"):a}function wc(a,b){b&&browser.runtime.lastError||browser.permissions.request({permissions:[a]},b)}function O(a){browser.runtime.lastError;a;!0}
URL.prototype.a="searchParams"in URL.prototype?function(a){return this.searchParams.get(a)}:function Wc(a){var c=Wc.cache||(Wc.cache={});return(a=(c[a]||(c[a]=new RegExp("[?&]"+escape(a)+"\\b(?:=([^&]*))?"))).exec(this.search))&&unescape(a[1]||"")};const ac=Function.bind.bind(function(a){return this[a]}),Bc=Function.bind.bind(function(a){return a&&a[this]}),Sc=H.TextDecoder?TextDecoder.prototype.decode.bind(new TextDecoder("ascii")):function(){return""};var V=Object.values;V||(V=function(a){return Object.keys(a).map(ac(a))});
Array.prototype.fill||(Array.prototype.fill=function(a){for(var b=this.length;b--;this[b]=a);return this});String.prototype.replaceAll||(String.prototype.replaceAll=function(a,b){return this.split(a).join(b)});
const Ib=[[!0,-8,"menu_download_link","link,image,video",M.prototype.Ra],[!0,-8,"menu_download_link","page,frame,editable",M.prototype.Ra,Ga],[!0,-8,"menu_download_selected","selection",M.prototype.fb],[!0,-9,"menu_download_all","page,frame,editable",M.prototype.fb],[B,-8,"menu_download_item","link",M.prototype.Ra,["chrome://downloads/*"]]],Eb=Jb("tooltip_title"),Gb=Jb("tooltip_disabled"),Hb=Jb("tooltip_error"),Fb="\n"+Jb("tooltip_text");N.splice(0);Tc();
